// Generated by gencpp from file groundserver/extArdu.msg
// DO NOT EDIT!


#ifndef GROUNDSERVER_MESSAGE_EXTARDU_H
#define GROUNDSERVER_MESSAGE_EXTARDU_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace groundserver
{
template <class ContainerAllocator>
struct extArdu_
{
  typedef extArdu_<ContainerAllocator> Type;

  extArdu_()
    : arduYaw(0.0)
    , arduThrottle(0.0)
    , arduPitch(0.0)
    , arduRoll(0.0)
    , arduArmGripOn(0)
    , arduArmGripOff(0)
    , arduStabilizeMode(0)
    , arduRemoteArmed(0)  {
    }
  extArdu_(const ContainerAllocator& _alloc)
    : arduYaw(0.0)
    , arduThrottle(0.0)
    , arduPitch(0.0)
    , arduRoll(0.0)
    , arduArmGripOn(0)
    , arduArmGripOff(0)
    , arduStabilizeMode(0)
    , arduRemoteArmed(0)  {
  (void)_alloc;
    }



   typedef float _arduYaw_type;
  _arduYaw_type arduYaw;

   typedef float _arduThrottle_type;
  _arduThrottle_type arduThrottle;

   typedef float _arduPitch_type;
  _arduPitch_type arduPitch;

   typedef float _arduRoll_type;
  _arduRoll_type arduRoll;

   typedef int32_t _arduArmGripOn_type;
  _arduArmGripOn_type arduArmGripOn;

   typedef int32_t _arduArmGripOff_type;
  _arduArmGripOff_type arduArmGripOff;

   typedef int32_t _arduStabilizeMode_type;
  _arduStabilizeMode_type arduStabilizeMode;

   typedef int32_t _arduRemoteArmed_type;
  _arduRemoteArmed_type arduRemoteArmed;




  typedef boost::shared_ptr< ::groundserver::extArdu_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::groundserver::extArdu_<ContainerAllocator> const> ConstPtr;

}; // struct extArdu_

typedef ::groundserver::extArdu_<std::allocator<void> > extArdu;

typedef boost::shared_ptr< ::groundserver::extArdu > extArduPtr;
typedef boost::shared_ptr< ::groundserver::extArdu const> extArduConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::groundserver::extArdu_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::groundserver::extArdu_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace groundserver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geographic_msgs': ['/opt/ros/kinetic/share/geographic_msgs/cmake/../msg'], 'groundserver': ['/home/mfikih15/Documents/kapalTenggelam/serverGabut/src/groundserver/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'mavros_msgs': ['/opt/ros/kinetic/share/mavros_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'uuid_msgs': ['/opt/ros/kinetic/share/uuid_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::groundserver::extArdu_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::groundserver::extArdu_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::groundserver::extArdu_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::groundserver::extArdu_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::groundserver::extArdu_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::groundserver::extArdu_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::groundserver::extArdu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "444e27210a1cc7337dd2f2ca6321c819";
  }

  static const char* value(const ::groundserver::extArdu_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x444e27210a1cc733ULL;
  static const uint64_t static_value2 = 0x7dd2f2ca6321c819ULL;
};

template<class ContainerAllocator>
struct DataType< ::groundserver::extArdu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "groundserver/extArdu";
  }

  static const char* value(const ::groundserver::extArdu_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::groundserver::extArdu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 arduYaw \n\
float32 arduThrottle\n\
float32 arduPitch\n\
float32 arduRoll\n\
int32 arduArmGripOn\n\
int32 arduArmGripOff\n\
int32 arduStabilizeMode\n\
int32 arduRemoteArmed\n\
";
  }

  static const char* value(const ::groundserver::extArdu_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::groundserver::extArdu_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.arduYaw);
      stream.next(m.arduThrottle);
      stream.next(m.arduPitch);
      stream.next(m.arduRoll);
      stream.next(m.arduArmGripOn);
      stream.next(m.arduArmGripOff);
      stream.next(m.arduStabilizeMode);
      stream.next(m.arduRemoteArmed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct extArdu_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::groundserver::extArdu_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::groundserver::extArdu_<ContainerAllocator>& v)
  {
    s << indent << "arduYaw: ";
    Printer<float>::stream(s, indent + "  ", v.arduYaw);
    s << indent << "arduThrottle: ";
    Printer<float>::stream(s, indent + "  ", v.arduThrottle);
    s << indent << "arduPitch: ";
    Printer<float>::stream(s, indent + "  ", v.arduPitch);
    s << indent << "arduRoll: ";
    Printer<float>::stream(s, indent + "  ", v.arduRoll);
    s << indent << "arduArmGripOn: ";
    Printer<int32_t>::stream(s, indent + "  ", v.arduArmGripOn);
    s << indent << "arduArmGripOff: ";
    Printer<int32_t>::stream(s, indent + "  ", v.arduArmGripOff);
    s << indent << "arduStabilizeMode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.arduStabilizeMode);
    s << indent << "arduRemoteArmed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.arduRemoteArmed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GROUNDSERVER_MESSAGE_EXTARDU_H
