// Generated by gencpp from file groundserver/usbIp.msg
// DO NOT EDIT!


#ifndef GROUNDSERVER_MESSAGE_USBIP_H
#define GROUNDSERVER_MESSAGE_USBIP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace groundserver
{
template <class ContainerAllocator>
struct usbIp_
{
  typedef usbIp_<ContainerAllocator> Type;

  usbIp_()
    : throttle(0.0)
    , steering(0.0)
    , servoGrip(0.0)
    , altitude(0.0)  {
    }
  usbIp_(const ContainerAllocator& _alloc)
    : throttle(0.0)
    , steering(0.0)
    , servoGrip(0.0)
    , altitude(0.0)  {
  (void)_alloc;
    }



   typedef float _throttle_type;
  _throttle_type throttle;

   typedef float _steering_type;
  _steering_type steering;

   typedef float _servoGrip_type;
  _servoGrip_type servoGrip;

   typedef float _altitude_type;
  _altitude_type altitude;




  typedef boost::shared_ptr< ::groundserver::usbIp_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::groundserver::usbIp_<ContainerAllocator> const> ConstPtr;

}; // struct usbIp_

typedef ::groundserver::usbIp_<std::allocator<void> > usbIp;

typedef boost::shared_ptr< ::groundserver::usbIp > usbIpPtr;
typedef boost::shared_ptr< ::groundserver::usbIp const> usbIpConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::groundserver::usbIp_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::groundserver::usbIp_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace groundserver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geographic_msgs': ['/opt/ros/kinetic/share/geographic_msgs/cmake/../msg'], 'groundserver': ['/home/mfikih15/Documents/kapalTenggelam/serverGabut/src/groundserver/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'mavros_msgs': ['/opt/ros/kinetic/share/mavros_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'uuid_msgs': ['/opt/ros/kinetic/share/uuid_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::groundserver::usbIp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::groundserver::usbIp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::groundserver::usbIp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::groundserver::usbIp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::groundserver::usbIp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::groundserver::usbIp_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::groundserver::usbIp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5a9b5f9885099077c58386bfdab1c9a0";
  }

  static const char* value(const ::groundserver::usbIp_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5a9b5f9885099077ULL;
  static const uint64_t static_value2 = 0xc58386bfdab1c9a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::groundserver::usbIp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "groundserver/usbIp";
  }

  static const char* value(const ::groundserver::usbIp_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::groundserver::usbIp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 throttle\n\
float32 steering\n\
float32 servoGrip\n\
float32 altitude\n\
";
  }

  static const char* value(const ::groundserver::usbIp_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::groundserver::usbIp_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.throttle);
      stream.next(m.steering);
      stream.next(m.servoGrip);
      stream.next(m.altitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct usbIp_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::groundserver::usbIp_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::groundserver::usbIp_<ContainerAllocator>& v)
  {
    s << indent << "throttle: ";
    Printer<float>::stream(s, indent + "  ", v.throttle);
    s << indent << "steering: ";
    Printer<float>::stream(s, indent + "  ", v.steering);
    s << indent << "servoGrip: ";
    Printer<float>::stream(s, indent + "  ", v.servoGrip);
    s << indent << "altitude: ";
    Printer<float>::stream(s, indent + "  ", v.altitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GROUNDSERVER_MESSAGE_USBIP_H
