# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from groundserver/extArdu.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class extArdu(genpy.Message):
  _md5sum = "444e27210a1cc7337dd2f2ca6321c819"
  _type = "groundserver/extArdu"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 arduYaw 
float32 arduThrottle
float32 arduPitch
float32 arduRoll
int32 arduArmGripOn
int32 arduArmGripOff
int32 arduStabilizeMode
int32 arduRemoteArmed
"""
  __slots__ = ['arduYaw','arduThrottle','arduPitch','arduRoll','arduArmGripOn','arduArmGripOff','arduStabilizeMode','arduRemoteArmed']
  _slot_types = ['float32','float32','float32','float32','int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       arduYaw,arduThrottle,arduPitch,arduRoll,arduArmGripOn,arduArmGripOff,arduStabilizeMode,arduRemoteArmed

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(extArdu, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.arduYaw is None:
        self.arduYaw = 0.
      if self.arduThrottle is None:
        self.arduThrottle = 0.
      if self.arduPitch is None:
        self.arduPitch = 0.
      if self.arduRoll is None:
        self.arduRoll = 0.
      if self.arduArmGripOn is None:
        self.arduArmGripOn = 0
      if self.arduArmGripOff is None:
        self.arduArmGripOff = 0
      if self.arduStabilizeMode is None:
        self.arduStabilizeMode = 0
      if self.arduRemoteArmed is None:
        self.arduRemoteArmed = 0
    else:
      self.arduYaw = 0.
      self.arduThrottle = 0.
      self.arduPitch = 0.
      self.arduRoll = 0.
      self.arduArmGripOn = 0
      self.arduArmGripOff = 0
      self.arduStabilizeMode = 0
      self.arduRemoteArmed = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4f4i().pack(_x.arduYaw, _x.arduThrottle, _x.arduPitch, _x.arduRoll, _x.arduArmGripOn, _x.arduArmGripOff, _x.arduStabilizeMode, _x.arduRemoteArmed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.arduYaw, _x.arduThrottle, _x.arduPitch, _x.arduRoll, _x.arduArmGripOn, _x.arduArmGripOff, _x.arduStabilizeMode, _x.arduRemoteArmed,) = _get_struct_4f4i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4f4i().pack(_x.arduYaw, _x.arduThrottle, _x.arduPitch, _x.arduRoll, _x.arduArmGripOn, _x.arduArmGripOff, _x.arduStabilizeMode, _x.arduRemoteArmed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.arduYaw, _x.arduThrottle, _x.arduPitch, _x.arduRoll, _x.arduArmGripOn, _x.arduArmGripOff, _x.arduStabilizeMode, _x.arduRemoteArmed,) = _get_struct_4f4i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4f4i = None
def _get_struct_4f4i():
    global _struct_4f4i
    if _struct_4f4i is None:
        _struct_4f4i = struct.Struct("<4f4i")
    return _struct_4f4i
